--View to analize the total sales, raw and real profit

CREATE OR REPLACE VIEW PIPELINE.GLOBAL_TRANSACTIONS.TOTAL_SALES(
    TOTAL_ITEMS_SOLD,
    RAW_PROFIT,
    REAL_PROFIT
) AS
SELECT
    SUM(QUANTITY_OF_ITEMS_SOLD) AS TOTAL_ITEMS_SOLD,
    SUM((QUANTITY_OF_ITEMS_SOLD * UNIT_PRICE)) AS RAW_PROFIT,
    SUM((QUANTITY_OF_ITEMS_SOLD * UNIT_PRICE) - DISCOUNT) AS REAL_PROFIT
FROM PIPELINE.GLOBAL_TRANSACTIONS.SALES;

SELECT * FROM TOTAL_SALES;